rules:
  unpinned-uses:
    ignore:
      - axosyslog-image-test.yml
  unpinned-images:
    ignore:
      - devshell.yml
      - devshell_light_valgrind.yml
  dangerous-triggers:
    ignore:
      - comment-cfg-grammar-changes.yml
