name: Release axosyslog-light

on:
  push:
    tags:
      - 'light-v*.*.*'
  workflow_dispatch:

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check tag matches version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/light-v}
          SOURCE_VERSION=$(poetry version -s)
          if [ "$TAG_VERSION" != "$SOURCE_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match the source's version ($SOURCE_VERSION). Either update the source version or the tag."
            exit 1
          fi
        working-directory: tests/light

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: poetry install
        working-directory: tests/light

      - name: Build package
        run: poetry build
        working-directory: tests/light

      - name: upload dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: tests/light/dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      # https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-pypi
      # https://github.com/pypa/gh-action-pypi-publish/tree/release/v1.12
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        # TODO: remove for real PyPi release
        with:
          repository-url: https://test.pypi.org/legacy/
